<?php

declare(strict_types=1);

namespace Neo\Core\Controller\Command;

use Neo\Core\Console\Abstract\AbstractCommand;
use Neo\Core\Console\Attribute\Command;
use Neo\Core\Console\Enum\ExitCode;
use Neo\Core\Console\Input\Input;
use Neo\Core\Console\Output\Output;
use Neo\Core\Controller\Interface\ControllerExtensionInterface;
use Neo\Core\DI\Container;
use Neo\Core\Package\Interface\PackageInterface;
use Neo\Core\Utils\Scanner\ScannerFileManager;

#[Command(
    name: 'make:ide-helper',
    description: 'Generate an IDE helper stub listing every method available on AbstractController',
    category: 'Controller',
)]
final class MakeIdeHelperCommand extends AbstractCommand
{
    public function __construct(
        private Container $container
    ) {
    }

    public function do(Input $input, Output $output): ExitCode
    {
        $basePath = realpath(__DIR__ . '/../../../../');

        $scanPaths = [
            $basePath . '/neo', $basePath . '/src'
        ];

        if ($this->container->has('packages')) {
            /** @var array<int, PackageInterface> $packages */
            $packages = $this->container->get('packages');
            foreach ($packages as $package) {
                $scanPaths[] = $package->getPath();
            }
        }

        $results = new ScannerFileManager()
            ->paths($scanPaths)
            ->withFilenameSuffix('Extension.php')
            ->withExcludedSegment('vendor', '.git', 'node_modules')
            ->scan();

        $methods = [];

        foreach ($results as $result) {
            $fqcn = $result->getFqcn();

            if (!class_exists($fqcn)) {
                continue;
            }

            $ref = new \ReflectionClass($fqcn);

            if (!$ref->implementsInterface(ControllerExtensionInterface::class)) {
                continue;
            }

            $doc = $ref->getDocComment();
            if ($doc === false) {
                continue;
            }

            if (preg_match_all('/@method\s+(.+)$/m', $doc, $matches)) {
                foreach ($matches[1] as $signature) {
                    $methods[trim($signature)] = trim($signature);
                }
            }
        }

        ksort($methods);

        $lines = array_map(static fn(string $m) => " * @method $m", $methods);
        $docblock = implode("\n", $lines);

        $stub = <<<PHP
<?php
// This file is generated by `php bin/neo make:ide-helper`.
// It is never loaded at runtime — it only exists so IDEs can autocomplete
// \$this->getXxx() calls inside controllers, aggregated from every
// ControllerExtensionInterface implementation found in neo/, src/, and
// installed packages. Do not edit by hand, and do not require/include it.

namespace Neo\Core\Controller;

/**
$docblock
 */
abstract class AbstractController
{
}

PHP;

        $outputDir = $basePath . '/.ide-helper';
        if (!is_dir($outputDir)) {
            mkdir($outputDir, 0755, true);
        }

        file_put_contents($outputDir . '/AbstractController.php', $stub);

        Output::success('IDE helper generated: .ide-helper/AbstractController.php');
        Output::info(count($methods) . ' method(s) found across ' . count($scanPaths) . ' scanned path(s).');

        return ExitCode::SUCCESS;
    }
}