<?php
// This file is generated by `php bin/neo make:ide-helper`.
// It is never loaded at runtime — it only exists so IDEs can autocomplete
// $this->getXxx() calls inside controllers, aggregated from every
// ControllerExtensionInterface implementation found in neo/, src/, and
// installed packages. Do not edit by hand, and do not require/include it.

namespace Neo\Core\Controller;

/**
 * @method \Neo\Core\Event\Interface\EventInterface dispatch(\Neo\Core\Event\Interface\EventInterface $event)
 * @method \Neo\Core\Http\Client\Cookie\Cookie getCookie()
 * @method \Neo\Core\Http\Client\Flash\Flash getFlash()
 * @method \Neo\Core\Http\Client\Session\Session getSession()
 * @method \Neo\Core\Http\Response\Types\JsonResponse json(array<string, mixed>|object $data, int $status = 200)
 * @method \Neo\Core\Http\Response\Types\JsonResponse jsonError(string $message, int $status = 400, array<string, mixed> $extra = [])
 * @method \Neo\Core\Http\Response\Types\JsonResponse jsonSuccess(array<string, mixed>|object $data = [], int $status = 200)
 * @method \Neo\Core\Http\Response\Types\RedirectResponse redirect(string $url, int $status = 302)
 * @method \Neo\Core\Http\Response\Types\RedirectResponse redirectBack(?string $fallbackRoute = null, array<string, string> $routeParams = [], int $code = 302)
 * @method \Neo\Core\Http\Response\Types\RedirectResponse redirectToPath(string $path, int $code = 302)
 * @method \Neo\Core\Http\Response\Types\RedirectResponse redirectToRoute(string $routeName, array<string, string> $params = [], array<string, mixed> $query = [])
 * @method \Neo\Core\Http\Response\Types\Response make()
 * @method \Neo\Core\Http\Response\Types\Response render(string $template, array<string, mixed> $params = [])
 * @method \Neo\Core\Security\Auth\AuthManager auth()
 * @method \Neo\Core\Security\Auth\PasswordManager getPasswordManager()
 * @method \Neo\Core\Security\Middleware\MiddlewareManager getMiddleware()
 * @method \Neo\Core\Utils\Cache\CacheManager getCache()
 * @method \Neo\Core\Utils\Config\ConfigManager getConfig()
 * @method \Neo\Core\Utils\Logger\LoggerManager getLogger()
 * @method \Neo\Core\Utils\Notification\NotificationManager getNotification()
 * @method \Neo\Core\Utils\Scanner\ScannerAttributeManager getScanner(string $classname)
 * @method \Neo\Core\Utils\Scanner\ScannerFileManager getFileScanner()
 * @method string generateUrl(string $routeName, array<string, string> $params = [], array<string, mixed> $query = [])
 * @method string getRedirectBack(?string $fallbackRoute = null, array<string, string> $routeParams = [])
 * @method string getRoutePath(string $routeName, array<string, string> $params = [], array<string, mixed> $query = [])
 * @method string template(string $template, array<string, mixed> $params = [])
 * @method string upload(string $field, string $name, array<int, string> $extensions, string $directory)
 */
abstract class AbstractController
{
}
