name: CI

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Validate Composer
        run: composer validate

      - name: Dump autoload
        run: composer dump-autoload --optimize

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --no-progress --memory-limit=1G